remote_theme: just-the-docs/just-the-docs

# Site settings
title: CIS Tutorials #title of the page
description: Enter description here
##baseurl: "/just-the-docs" # the subpath of your site, e.g. /blog #need to input
##url: "https://just-the-docs.github.io" # the base hostname & protocol for your site, e.g. http://example.com #need to input

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"
, "docs/tests/"
]

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/just-the-docs.png" #need to add a logo here later

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  heading_level: 2
  # Maximum amount of previews per search result
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  preview_words_after: 5
  # Set the search token separator
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/ #this is the default
  # Display the relative url in search results
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  button: false

# Enable or disable heading anchors
heading_anchors: true
  # Display the relative url in search results
  # Display the relative url in search results

# Aux links for the upper right navigation
#aux_links:
  #"Link name":
    #- "" #link would go here in the quotes
    
# Makes Aux links open in a new tab. Default is false
#aux_links_new_tab: false

# Sort order for navigation links
nav_sort: case_sensitive # Capital letters sorted before lowercase (default)


# Footer content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

