remote_theme: just-the-docs/just-the-docs

# Site settings
title: CIS Tutorials #title of the page
description: Enter description here
##baseurl: "/just-the-docs" # the subpath of your site, e.g. /blog #need to input
##url: "https://just-the-docs.github.io" # the base hostname & protocol for your site, e.g. http://example.com #need to input
